version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 500
      runas: root
  RemoveLock:
    - location: scripts/lock.sh
      timeout: 500
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 500
      runas: root
  Start:
    - location: scripts/start_server.sh
      timeout: 500
      runas: root