version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp
    # overwrite: true
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - file
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - directory
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu